# Generated by Django 2.2.4 on 2019-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='conclusao',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='contato',
            field=models.IntegerField(max_length=11, verbose_name='Telefone'),
        ),
    ]
