# Generated by Django 2.2.4 on 2019-11-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191117_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(max_length=1000, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='nome',
            field=models.TextField(max_length=100, verbose_name='Nome'),
        ),
    ]
