# Generated by Django 2.2.4 on 2019-11-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191117_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='nome',
            field=models.TextField(verbose_name='Nome'),
        ),
    ]
